name: Publicar paquete en GitHub Packages
on:
  push:
    branches:
      - master
jobs:
  publicar-paquete:             
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Configurar .npmrc
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@EduardoMaravilla'  
        
      - name: Instalar dependencias usando versiones de package-lock.json
        run: npm ci
      - name: Publicar paquete
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        